name: YouTube Sentiment Ingest

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary nltk pandas tqdm

      - name: Download NLTK data
        run: |
          source .venv/bin/activate
          python -m nltk.downloader vader_lexicon

      - name: Show DB host
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          python - <<'PY'
          import os
          from urllib.parse import urlparse
          u=os.environ['SUPABASE_DB_URL']
          host=urlparse(u).hostname
          print("DB host from secret:", host)
          PY

      # Force IPv4 by replacing hostname with its A-record (IPv4)
      - name: Run ingest script (force IPv4)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          YT_VIDEO_ID: ${{ secrets.YT_VIDEO_ID }}
        run: |
          source .venv/bin/activate
          export SUPABASE_DB_URL=$(python - <<'PY'
          import os, socket
          from urllib.parse import urlparse
          u=os.environ['SUPABASE_DB_URL']
          p=urlparse(u)
          host = p.hostname
          ipv4 = socket.gethostbyname(host)
          print(u.replace(host, ipv4))
          PY
          )
          echo "Using IPv4 DB URL:"
          echo "$SUPABASE_DB_URL" | sed -E 's#://([^:@/]+):([^@]+)@#://\1:<hidden>@#'
          python scripts/ingest_to_supabase.py
